@startuml
!theme plain
skinparam class {
    BackgroundColor<<Interface>> #A9DCDF
    BackgroundColor<<Enum>> #FFD966
}

package entity #D4C2FC {
    interface Entidade <<Interface>> {
        + getPosicaoX()
        + getPosicaoY()
        + getTipo()
    }

    enum TipoEntidade <<Enum>> {
        VAZIO
        ROBO
        OBSTACULO
        DESCONHECIDO
    }
}

' Relationships
Entidade <|-- TipoEntidade
@enduml