@startuml
!theme plain
skinparam package {
    BackgroundColor #F0F0F0
    BorderColor #AAAAAA
}

package ambiente #CCF2FF {
    [Ambiente]
    [ForaMapaException]
}

package comunicacao #FFE6CC {
    [Comunicavel]
    [CentralComunicacao]
    [ErroComunicacaoException]
}

package entity #D4C2FC {
    [Entidade]
    [TipoEntidade]
}

package menus #FFD8E6 {
    [MenuInterativo]
}

package obstaculos #FFF2CC {
    [ColisaoException]
    [Obstaculo]
    [TipoObstaculo]
}

package robos #DAF7A6 {
    [Robo]
    [RoboAereo]
    [RoboAleatorio]
    [RoboAtirador]
    [RoboTerrestre]
    [EstadoRobo]
}

package sensores #FFCC99 {
    [Sensor]
    [SensorProximidade]
    [SensorUmidade]
}

package utils #E6CCFF {
    [DistanceCalculator]
    [RandomNumberGenerator]
    [RandomStringGenerator]
}

' Package dependencies
ambiente --> entity
ambiente --> robos
ambiente --> obstaculos
comunicacao --> robos
menus --> ambiente
menus --> robos
obstaculos --> entity
obstaculos --> robos
robos --> entity
robos --> ambiente
robos --> comunicacao
robos --> sensores
robos --> utils
sensores --> robos
sensores --> entity
utils --> entity

@enduml