@startuml
!theme plain
skinparam class {
    BackgroundColor<<Class>> #D5E8D4
}

package utils #E6CCFF {
    class DistanceCalculator {
        + calculateDistance()
    }

    class RandomNumberGenerator {
        + generate()
    }

    class RandomStringGenerator {
        + generatePrintableRandomString()
    }
}

' External references
interface "Entidade" as Entidade #D4C2FC

' Relationships
DistanceCalculator ..> Entidade: uses
@enduml